#!/bin/bash
echo "Hello. THis is MIguel. I will install your dependencies"
sudo apt install vim
sudo apt install g++
sudo apt install git
sudo apt install cmake
echo "That's all the depencies. Goodbye"
